runtime: php 
env: flex 
runtime_config: 
    document_root: . 
env_variables: 
    APP_LOG: errorlog
    GOOGLE_STORAGE_BUCKET: "cs348demo-279318.appspot.com"
    MYSQL_DBNAME: "pokemon"
    MYSQL_CONNECTION_NAME: "/cloudsql/cs348demo-279318:us-central1:cs348demo-db"
    MYSQL_USER: "root"
    MYSQL_PASSWORD: "password" 
    MYSQL_DSN: "mysql:dbname=cs348demo-db;unix_socket=/cloudsql/cs348demo-279318:us-central1:cs348demo-db"
beta_settings: 
    cloud_sql_instances: "cs348demo-279318:us-central1:cs348demo-db"
